/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using rma.Client;
using rma.Api;
// uncomment below to import models
//using rma.Model;

namespace rma.Test.Api
{
    /// <summary>
    ///  Class for testing RmaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RmaApiTests : IDisposable
    {
        private RmaApi instance;

        public RmaApiTests()
        {
            instance = new RmaApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RmaApi
            //Assert.IsType<RmaApi>(instance);
        }

        /// <summary>
        /// Test AddNote
        /// </summary>
        [Fact]
        public void AddNoteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaAddNoteRequest body = null;
            //var response = instance.AddNote(body);
            //Assert.IsType<RmaNoteResponse>(response);
        }

        /// <summary>
        /// Test ApproveReturn
        /// </summary>
        [Fact]
        public void ApproveReturnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaApproveReturnRequest body = null;
            //var response = instance.ApproveReturn(body);
            //Assert.IsType<RpcStatus>(response);
        }

        /// <summary>
        /// Test CancelReturn
        /// </summary>
        [Fact]
        public void CancelReturnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaCancelReturnRequest body = null;
            //var response = instance.CancelReturn(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ConfirmReturnApproveItems
        /// </summary>
        [Fact]
        public void ConfirmReturnApproveItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaConfirmReturnApproveItemsRequest body = null;
            //var response = instance.ConfirmReturnApproveItems(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CreateReturn
        /// </summary>
        [Fact]
        public void CreateReturnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaCreateReturnRequest body = null;
            //var response = instance.CreateReturn(body);
            //Assert.IsType<RmaReturnResponse>(response);
        }

        /// <summary>
        /// Test DeleteNote
        /// </summary>
        [Fact]
        public void DeleteNoteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaDeleteNoteRequest body = null;
            //var response = instance.DeleteNote(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test EditNote
        /// </summary>
        [Fact]
        public void EditNoteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaEditNoteRequest body = null;
            //var response = instance.EditNote(body);
            //Assert.IsType<RmaNoteResponse>(response);
        }

        /// <summary>
        /// Test GetReturn
        /// </summary>
        [Fact]
        public void GetReturnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaGetReturnRequest body = null;
            //var response = instance.GetReturn(body);
            //Assert.IsType<RmaReturnResponse>(response);
        }

        /// <summary>
        /// Test ListNotesByReturnId
        /// </summary>
        [Fact]
        public void ListNotesByReturnIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaListNotesByReturnIdRequest body = null;
            //var response = instance.ListNotesByReturnId(body);
            //Assert.IsType<RmaListNotesByReturnIdResponse>(response);
        }

        /// <summary>
        /// Test ListReturns
        /// </summary>
        [Fact]
        public void ListReturnsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaListReturnsRequest body = null;
            //var response = instance.ListReturns(body);
            //Assert.IsType<RmaListReturnsResponse>(response);
        }

        /// <summary>
        /// Test RefundReturn
        /// </summary>
        [Fact]
        public void RefundReturnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaRefundReturnRequest body = null;
            //var response = instance.RefundReturn(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test RejectReturn
        /// </summary>
        [Fact]
        public void RejectReturnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaRejectReturnRequest body = null;
            //var response = instance.RejectReturn(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SetReceivedItems
        /// </summary>
        [Fact]
        public void SetReceivedItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaSetReceivedItemsRequest body = null;
            //var response = instance.SetReceivedItems(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SkipReturnStatus
        /// </summary>
        [Fact]
        public void SkipReturnStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RmaSkipReturnStatusRequest body = null;
            //var response = instance.SkipReturnStatus(body);
            //Assert.IsType<Object>(response);
        }
    }
}
