/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rma.Client.OpenAPIDateConverter;

namespace rma.Model
{
    /// <summary>
    /// CreateReturnRequestProduct
    /// </summary>
    [DataContract(Name = "CreateReturnRequestProduct")]
    public partial class CreateReturnRequestProduct : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReturnRequestProduct" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateReturnRequestProduct() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReturnRequestProduct" /> class.
        /// </summary>
        /// <param name="grn">grn (required).</param>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="reason">reason.</param>
        /// <param name="note">note.</param>
        public CreateReturnRequestProduct(string grn = default(string), string quantity = default(string), string reason = default(string), string note = default(string))
        {
            // to ensure "grn" is required (not null)
            if (grn == null)
            {
                throw new ArgumentNullException("grn is a required property for CreateReturnRequestProduct and cannot be null");
            }
            this.Grn = grn;
            // to ensure "quantity" is required (not null)
            if (quantity == null)
            {
                throw new ArgumentNullException("quantity is a required property for CreateReturnRequestProduct and cannot be null");
            }
            this.Quantity = quantity;
            this.Reason = reason;
            this.Note = note;
        }

        /// <summary>
        /// Gets or Sets Grn
        /// </summary>
        [DataMember(Name = "grn", IsRequired = true, EmitDefaultValue = true)]
        public string Grn { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public string Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>
        [DataMember(Name = "note", EmitDefaultValue = false)]
        public string Note { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateReturnRequestProduct {\n");
            sb.Append("  Grn: ").Append(Grn).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
