/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rma.Client.OpenAPIDateConverter;

namespace rma.Model
{
    /// <summary>
    /// RmaApproveReturnRequest
    /// </summary>
    [DataContract(Name = "rmaApproveReturnRequest")]
    public partial class RmaApproveReturnRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RmaApproveReturnRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RmaApproveReturnRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RmaApproveReturnRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="refundShippingCost">refundShippingCost (required).</param>
        /// <param name="refundPaymentCost">refundPaymentCost (required).</param>
        /// <param name="items">items (required).</param>
        public RmaApproveReturnRequest(string tenantId = default(string), string id = default(string), bool refundShippingCost = default(bool), bool refundPaymentCost = default(bool), List<RmaApproveReturnRequestItem> items = default(List<RmaApproveReturnRequestItem>))
        {
            // to ensure "tenantId" is required (not null)
            if (tenantId == null)
            {
                throw new ArgumentNullException("tenantId is a required property for RmaApproveReturnRequest and cannot be null");
            }
            this.TenantId = tenantId;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for RmaApproveReturnRequest and cannot be null");
            }
            this.Id = id;
            this.RefundShippingCost = refundShippingCost;
            this.RefundPaymentCost = refundPaymentCost;
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for RmaApproveReturnRequest and cannot be null");
            }
            this.Items = items;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", IsRequired = true, EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets RefundShippingCost
        /// </summary>
        [DataMember(Name = "refundShippingCost", IsRequired = true, EmitDefaultValue = true)]
        public bool RefundShippingCost { get; set; }

        /// <summary>
        /// Gets or Sets RefundPaymentCost
        /// </summary>
        [DataMember(Name = "refundPaymentCost", IsRequired = true, EmitDefaultValue = true)]
        public bool RefundPaymentCost { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<RmaApproveReturnRequestItem> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RmaApproveReturnRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RefundShippingCost: ").Append(RefundShippingCost).Append("\n");
            sb.Append("  RefundPaymentCost: ").Append(RefundPaymentCost).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
