/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rma.Client.OpenAPIDateConverter;

namespace rma.Model
{
    /// <summary>
    /// RmaListNotesByReturnIdRequest
    /// </summary>
    [DataContract(Name = "rmaListNotesByReturnIdRequest")]
    public partial class RmaListNotesByReturnIdRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RmaListNotesByReturnIdRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RmaListNotesByReturnIdRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RmaListNotesByReturnIdRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId (required).</param>
        /// <param name="returnId">returnId (required).</param>
        /// <param name="pageSize">pageSize.</param>
        /// <param name="pageToken">pageToken.</param>
        /// <param name="sorts">sorts.</param>
        public RmaListNotesByReturnIdRequest(string tenantId = default(string), string returnId = default(string), long pageSize = default(long), string pageToken = default(string), List<RmaListNotesByReturnIdRequestSort> sorts = default(List<RmaListNotesByReturnIdRequestSort>))
        {
            // to ensure "tenantId" is required (not null)
            if (tenantId == null)
            {
                throw new ArgumentNullException("tenantId is a required property for RmaListNotesByReturnIdRequest and cannot be null");
            }
            this.TenantId = tenantId;
            // to ensure "returnId" is required (not null)
            if (returnId == null)
            {
                throw new ArgumentNullException("returnId is a required property for RmaListNotesByReturnIdRequest and cannot be null");
            }
            this.ReturnId = returnId;
            this.PageSize = pageSize;
            this.PageToken = pageToken;
            this.Sorts = sorts;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", IsRequired = true, EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets ReturnId
        /// </summary>
        [DataMember(Name = "returnId", IsRequired = true, EmitDefaultValue = true)]
        public string ReturnId { get; set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [DataMember(Name = "pageSize", EmitDefaultValue = false)]
        public long PageSize { get; set; }

        /// <summary>
        /// Gets or Sets PageToken
        /// </summary>
        [DataMember(Name = "pageToken", EmitDefaultValue = false)]
        public string PageToken { get; set; }

        /// <summary>
        /// Gets or Sets Sorts
        /// </summary>
        [DataMember(Name = "sorts", EmitDefaultValue = false)]
        public List<RmaListNotesByReturnIdRequestSort> Sorts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RmaListNotesByReturnIdRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  ReturnId: ").Append(ReturnId).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  PageToken: ").Append(PageToken).Append("\n");
            sb.Append("  Sorts: ").Append(Sorts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
