/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rma.Client.OpenAPIDateConverter;

namespace rma.Model
{
    /// <summary>
    /// RmaListReturnsRequestSort
    /// </summary>
    [DataContract(Name = "rmaListReturnsRequestSort")]
    public partial class RmaListReturnsRequestSort : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = true)]
        public RmaListReturnsRequestSortSortField Field { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public RmaSortOrder? Order { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RmaListReturnsRequestSort" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RmaListReturnsRequestSort()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="RmaListReturnsRequestSort" /> class.
        /// </summary>
        /// <param name="evaluationOrder">evaluation_order is the order in which the sort will be applied. The lower the number, the earlier the sort will be applied. (required).</param>
        /// <param name="field">field (required).</param>
        /// <param name="order">order.</param>
        public RmaListReturnsRequestSort(long evaluationOrder = default(long), RmaListReturnsRequestSortSortField field = default(RmaListReturnsRequestSortSortField), RmaSortOrder? order = default(RmaSortOrder?))
        {
            this.EvaluationOrder = evaluationOrder;
            this.Field = field;
            this.Order = order;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// evaluation_order is the order in which the sort will be applied. The lower the number, the earlier the sort will be applied.
        /// </summary>
        /// <value>evaluation_order is the order in which the sort will be applied. The lower the number, the earlier the sort will be applied.</value>
        [DataMember(Name = "evaluationOrder", IsRequired = true, EmitDefaultValue = true)]
        public long EvaluationOrder { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RmaListReturnsRequestSort {\n");
            sb.Append("  EvaluationOrder: ").Append(EvaluationOrder).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
