/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rma.Client.OpenAPIDateConverter;

namespace rma.Model
{
    /// <summary>
    /// Defines rmaRefundMethod
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RmaRefundMethod
    {
        /// <summary>
        /// Enum UNKNOWN for value: REFUND_METHOD_UNKNOWN
        /// </summary>
        [EnumMember(Value = "REFUND_METHOD_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum OFFLINE for value: REFUND_METHOD_OFFLINE
        /// </summary>
        [EnumMember(Value = "REFUND_METHOD_OFFLINE")]
        OFFLINE = 2,

        /// <summary>
        /// Enum COUPON for value: REFUND_METHOD_COUPON
        /// </summary>
        [EnumMember(Value = "REFUND_METHOD_COUPON")]
        COUPON = 3,

        /// <summary>
        /// Enum SAMEASPAYMENT for value: REFUND_METHOD_SAME_AS_PAYMENT
        /// </summary>
        [EnumMember(Value = "REFUND_METHOD_SAME_AS_PAYMENT")]
        SAMEASPAYMENT = 4
    }

}
