/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing ListReturnsRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListReturnsRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListReturnsRequestFilter
        //private ListReturnsRequestFilter instance;

        public ListReturnsRequestFilterTests()
        {
            // TODO uncomment below to create an instance of ListReturnsRequestFilter
            //instance = new ListReturnsRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListReturnsRequestFilter
        /// </summary>
        [Fact]
        public void ListReturnsRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListReturnsRequestFilter
            //Assert.IsType<ListReturnsRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'SearchTerms'
        /// </summary>
        [Fact]
        public void SearchTermsTest()
        {
            // TODO unit test for the property 'SearchTerms'
        }

        /// <summary>
        /// Test the property 'ReturnIds'
        /// </summary>
        [Fact]
        public void ReturnIdsTest()
        {
            // TODO unit test for the property 'ReturnIds'
        }

        /// <summary>
        /// Test the property 'ReturnStatus'
        /// </summary>
        [Fact]
        public void ReturnStatusTest()
        {
            // TODO unit test for the property 'ReturnStatus'
        }

        /// <summary>
        /// Test the property 'OrderGrns'
        /// </summary>
        [Fact]
        public void OrderGrnsTest()
        {
            // TODO unit test for the property 'OrderGrns'
        }

        /// <summary>
        /// Test the property 'OrderNumbers'
        /// </summary>
        [Fact]
        public void OrderNumbersTest()
        {
            // TODO unit test for the property 'OrderNumbers'
        }

        /// <summary>
        /// Test the property 'OrderItemGrns'
        /// </summary>
        [Fact]
        public void OrderItemGrnsTest()
        {
            // TODO unit test for the property 'OrderItemGrns'
        }

        /// <summary>
        /// Test the property 'OrderItemSkus'
        /// </summary>
        [Fact]
        public void OrderItemSkusTest()
        {
            // TODO unit test for the property 'OrderItemSkus'
        }

        /// <summary>
        /// Test the property 'CustomerGrns'
        /// </summary>
        [Fact]
        public void CustomerGrnsTest()
        {
            // TODO unit test for the property 'CustomerGrns'
        }

        /// <summary>
        /// Test the property 'CustomerEmails'
        /// </summary>
        [Fact]
        public void CustomerEmailsTest()
        {
            // TODO unit test for the property 'CustomerEmails'
        }

        /// <summary>
        /// Test the property 'CreatedAtStart'
        /// </summary>
        [Fact]
        public void CreatedAtStartTest()
        {
            // TODO unit test for the property 'CreatedAtStart'
        }

        /// <summary>
        /// Test the property 'CreatedAtEnd'
        /// </summary>
        [Fact]
        public void CreatedAtEndTest()
        {
            // TODO unit test for the property 'CreatedAtEnd'
        }
    }
}
