/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDataSubtotal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDataSubtotalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDataSubtotal
        //private OrderDataSubtotal instance;

        public OrderDataSubtotalTests()
        {
            // TODO uncomment below to create an instance of OrderDataSubtotal
            //instance = new OrderDataSubtotal();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDataSubtotal
        /// </summary>
        [Fact]
        public void OrderDataSubtotalInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDataSubtotal
            //Assert.IsType<OrderDataSubtotal>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
