/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDataSubtotalCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDataSubtotalCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDataSubtotalCode
        //private OrderDataSubtotalCode instance;

        public OrderDataSubtotalCodeTests()
        {
            // TODO uncomment below to create an instance of OrderDataSubtotalCode
            //instance = new OrderDataSubtotalCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDataSubtotalCode
        /// </summary>
        [Fact]
        public void OrderDataSubtotalCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDataSubtotalCode
            //Assert.IsType<OrderDataSubtotalCode>(instance);
        }
    }
}
