/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDataTotalCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDataTotalCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDataTotalCode
        //private OrderDataTotalCode instance;

        public OrderDataTotalCodeTests()
        {
            // TODO uncomment below to create an instance of OrderDataTotalCode
            //instance = new OrderDataTotalCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDataTotalCode
        /// </summary>
        [Fact]
        public void OrderDataTotalCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDataTotalCode
            //Assert.IsType<OrderDataTotalCode>(instance);
        }
    }
}
