/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaAddNoteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaAddNoteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaAddNoteRequest
        //private RmaAddNoteRequest instance;

        public RmaAddNoteRequestTests()
        {
            // TODO uncomment below to create an instance of RmaAddNoteRequest
            //instance = new RmaAddNoteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaAddNoteRequest
        /// </summary>
        [Fact]
        public void RmaAddNoteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaAddNoteRequest
            //Assert.IsType<RmaAddNoteRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ReturnId'
        /// </summary>
        [Fact]
        public void ReturnIdTest()
        {
            // TODO unit test for the property 'ReturnId'
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
    }
}
