/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaConfirmReturnApproveItemsRequestItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaConfirmReturnApproveItemsRequestItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaConfirmReturnApproveItemsRequestItem
        //private RmaConfirmReturnApproveItemsRequestItem instance;

        public RmaConfirmReturnApproveItemsRequestItemTests()
        {
            // TODO uncomment below to create an instance of RmaConfirmReturnApproveItemsRequestItem
            //instance = new RmaConfirmReturnApproveItemsRequestItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaConfirmReturnApproveItemsRequestItem
        /// </summary>
        [Fact]
        public void RmaConfirmReturnApproveItemsRequestItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaConfirmReturnApproveItemsRequestItem
            //Assert.IsType<RmaConfirmReturnApproveItemsRequestItem>(instance);
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
