/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaCreateReturnRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaCreateReturnRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaCreateReturnRequest
        //private RmaCreateReturnRequest instance;

        public RmaCreateReturnRequestTests()
        {
            // TODO uncomment below to create an instance of RmaCreateReturnRequest
            //instance = new RmaCreateReturnRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaCreateReturnRequest
        /// </summary>
        [Fact]
        public void RmaCreateReturnRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaCreateReturnRequest
            //Assert.IsType<RmaCreateReturnRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'OrderGrn'
        /// </summary>
        [Fact]
        public void OrderGrnTest()
        {
            // TODO unit test for the property 'OrderGrn'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

        /// <summary>
        /// Test the property 'PreferredRefundMethod'
        /// </summary>
        [Fact]
        public void PreferredRefundMethodTest()
        {
            // TODO unit test for the property 'PreferredRefundMethod'
        }

        /// <summary>
        /// Test the property 'RefundShippingCost'
        /// </summary>
        [Fact]
        public void RefundShippingCostTest()
        {
            // TODO unit test for the property 'RefundShippingCost'
        }

        /// <summary>
        /// Test the property 'RefundPaymentCost'
        /// </summary>
        [Fact]
        public void RefundPaymentCostTest()
        {
            // TODO unit test for the property 'RefundPaymentCost'
        }

        /// <summary>
        /// Test the property 'CustomerInfo'
        /// </summary>
        [Fact]
        public void CustomerInfoTest()
        {
            // TODO unit test for the property 'CustomerInfo'
        }

        /// <summary>
        /// Test the property 'ReturnAddress'
        /// </summary>
        [Fact]
        public void ReturnAddressTest()
        {
            // TODO unit test for the property 'ReturnAddress'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
    }
}
