/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaCurrencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaCurrency
        //private RmaCurrency instance;

        public RmaCurrencyTests()
        {
            // TODO uncomment below to create an instance of RmaCurrency
            //instance = new RmaCurrency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaCurrency
        /// </summary>
        [Fact]
        public void RmaCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaCurrency
            //Assert.IsType<RmaCurrency>(instance);
        }
    }
}
