/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaCustomerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaCustomerInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaCustomerInfo
        //private RmaCustomerInfo instance;

        public RmaCustomerInfoTests()
        {
            // TODO uncomment below to create an instance of RmaCustomerInfo
            //instance = new RmaCustomerInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaCustomerInfo
        /// </summary>
        [Fact]
        public void RmaCustomerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaCustomerInfo
            //Assert.IsType<RmaCustomerInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Fact]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }

        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }
    }
}
