/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaListNotesByReturnIdResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaListNotesByReturnIdResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaListNotesByReturnIdResponse
        //private RmaListNotesByReturnIdResponse instance;

        public RmaListNotesByReturnIdResponseTests()
        {
            // TODO uncomment below to create an instance of RmaListNotesByReturnIdResponse
            //instance = new RmaListNotesByReturnIdResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaListNotesByReturnIdResponse
        /// </summary>
        [Fact]
        public void RmaListNotesByReturnIdResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaListNotesByReturnIdResponse
            //Assert.IsType<RmaListNotesByReturnIdResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
