/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaListReturnsRequestSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaListReturnsRequestSortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaListReturnsRequestSort
        //private RmaListReturnsRequestSort instance;

        public RmaListReturnsRequestSortTests()
        {
            // TODO uncomment below to create an instance of RmaListReturnsRequestSort
            //instance = new RmaListReturnsRequestSort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaListReturnsRequestSort
        /// </summary>
        [Fact]
        public void RmaListReturnsRequestSortInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaListReturnsRequestSort
            //Assert.IsType<RmaListReturnsRequestSort>(instance);
        }

        /// <summary>
        /// Test the property 'EvaluationOrder'
        /// </summary>
        [Fact]
        public void EvaluationOrderTest()
        {
            // TODO unit test for the property 'EvaluationOrder'
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
