/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaListReturnsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaListReturnsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaListReturnsResponse
        //private RmaListReturnsResponse instance;

        public RmaListReturnsResponseTests()
        {
            // TODO uncomment below to create an instance of RmaListReturnsResponse
            //instance = new RmaListReturnsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaListReturnsResponse
        /// </summary>
        [Fact]
        public void RmaListReturnsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaListReturnsResponse
            //Assert.IsType<RmaListReturnsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Returns'
        /// </summary>
        [Fact]
        public void ReturnsTest()
        {
            // TODO unit test for the property 'Returns'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
