/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaRejectReturnRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaRejectReturnRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaRejectReturnRequest
        //private RmaRejectReturnRequest instance;

        public RmaRejectReturnRequestTests()
        {
            // TODO uncomment below to create an instance of RmaRejectReturnRequest
            //instance = new RmaRejectReturnRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaRejectReturnRequest
        /// </summary>
        [Fact]
        public void RmaRejectReturnRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaRejectReturnRequest
            //Assert.IsType<RmaRejectReturnRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
