/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaReturnResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaReturnResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaReturnResponse
        //private RmaReturnResponse instance;

        public RmaReturnResponseTests()
        {
            // TODO uncomment below to create an instance of RmaReturnResponse
            //instance = new RmaReturnResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaReturnResponse
        /// </summary>
        [Fact]
        public void RmaReturnResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaReturnResponse
            //Assert.IsType<RmaReturnResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'OrderGrn'
        /// </summary>
        [Fact]
        public void OrderGrnTest()
        {
            // TODO unit test for the property 'OrderGrn'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

        /// <summary>
        /// Test the property 'PreferredRefundMethod'
        /// </summary>
        [Fact]
        public void PreferredRefundMethodTest()
        {
            // TODO unit test for the property 'PreferredRefundMethod'
        }

        /// <summary>
        /// Test the property 'RefundShippingCost'
        /// </summary>
        [Fact]
        public void RefundShippingCostTest()
        {
            // TODO unit test for the property 'RefundShippingCost'
        }

        /// <summary>
        /// Test the property 'RefundPaymentCost'
        /// </summary>
        [Fact]
        public void RefundPaymentCostTest()
        {
            // TODO unit test for the property 'RefundPaymentCost'
        }

        /// <summary>
        /// Test the property 'CustomerInfo'
        /// </summary>
        [Fact]
        public void CustomerInfoTest()
        {
            // TODO unit test for the property 'CustomerInfo'
        }

        /// <summary>
        /// Test the property 'ReturnAddress'
        /// </summary>
        [Fact]
        public void ReturnAddressTest()
        {
            // TODO unit test for the property 'ReturnAddress'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

        /// <summary>
        /// Test the property 'History'
        /// </summary>
        [Fact]
        public void HistoryTest()
        {
            // TODO unit test for the property 'History'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'OrderData'
        /// </summary>
        [Fact]
        public void OrderDataTest()
        {
            // TODO unit test for the property 'OrderData'
        }
    }
}
