/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaReturnHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaReturnHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaReturnHistory
        //private RmaReturnHistory instance;

        public RmaReturnHistoryTests()
        {
            // TODO uncomment below to create an instance of RmaReturnHistory
            //instance = new RmaReturnHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaReturnHistory
        /// </summary>
        [Fact]
        public void RmaReturnHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaReturnHistory
            //Assert.IsType<RmaReturnHistory>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
    }
}
