/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaReturnProductProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaReturnProductPropertyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaReturnProductProperty
        //private RmaReturnProductProperty instance;

        public RmaReturnProductPropertyTests()
        {
            // TODO uncomment below to create an instance of RmaReturnProductProperty
            //instance = new RmaReturnProductProperty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaReturnProductProperty
        /// </summary>
        [Fact]
        public void RmaReturnProductPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaReturnProductProperty
            //Assert.IsType<RmaReturnProductProperty>(instance);
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
    }
}
