/*
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rma.Model;
using rma.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rma.Test.Model
{
    /// <summary>
    ///  Class for testing RmaReturnProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RmaReturnProductTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RmaReturnProduct
        //private RmaReturnProduct instance;

        public RmaReturnProductTests()
        {
            // TODO uncomment below to create an instance of RmaReturnProduct
            //instance = new RmaReturnProduct();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RmaReturnProduct
        /// </summary>
        [Fact]
        public void RmaReturnProductInstanceTest()
        {
            // TODO uncomment below to test "IsType" RmaReturnProduct
            //Assert.IsType<RmaReturnProduct>(instance);
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'Requested'
        /// </summary>
        [Fact]
        public void RequestedTest()
        {
            // TODO unit test for the property 'Requested'
        }

        /// <summary>
        /// Test the property 'Approved'
        /// </summary>
        [Fact]
        public void ApprovedTest()
        {
            // TODO unit test for the property 'Approved'
        }

        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Fact]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }

        /// <summary>
        /// Test the property 'Refunded'
        /// </summary>
        [Fact]
        public void RefundedTest()
        {
            // TODO unit test for the property 'Refunded'
        }
    }
}
